from __future__ import annotations

from dataclasses import replace
from datetime import date

import pandas as pd

from sales_forecast.config import OutputConfig, load_config
from sales_forecast.report import generate_report


def test_generate_report_writes_five_dated_markdown_files(tmp_path):
    config = _config_with_outputs(tmp_path)
    _write_model_comparison(config.output.evaluation_dir)
    _write_model_evaluation_predictions(config.output.evaluation_dir)
    _write_forecasts(config.output.forecast_dir)
    _write_source_data(config.data.path)

    paths = generate_report(
        config,
        output=tmp_path / "custom_comparison.md",
        report_date=date(2026, 7, 4),
    )

    assert [path.name for path in paths] == [
        "custom_comparison_20260704.md",
        "linear_regression_report_20260704.md",
        "lightgbm_report_20260704.md",
        "prophet_report_20260704.md",
        "sarimax_report_20260704.md",
    ]
    for path in paths:
        assert path.exists()
        assert path.parent.name == "20260704"
        assert path.suffix == ".md"

    # Verify PNG generation
    figures_dir = tmp_path / "20260704" / "figures"
    assert (figures_dir / "accuracy_ranking_20260704.png").exists()
    assert (figures_dir / "forecast_range_comparison_20260704.png").exists()
    for model in ["linear_regression", "lightgbm", "prophet", "sarimax"]:
        assert (figures_dir / f"{model}_evaluation_20260704.png").exists()
        assert (figures_dir / f"{model}_forecast_20260704.png").exists()


def test_generate_report_includes_required_sections(tmp_path):
    config = _config_with_outputs(tmp_path)
    _write_model_comparison(config.output.evaluation_dir)
    _write_model_evaluation_predictions(config.output.evaluation_dir)
    _write_forecasts(config.output.forecast_dir)
    _write_source_data(config.data.path)

    paths = generate_report(config, report_date=date(2026, 7, 4))

    comparison = paths[0].read_text(encoding="utf-8")
    assert "## Model Comparison" in comparison
    assert "## Accuracy Ranking" in comparison
    assert "### Accuracy Ranking Visualization" in comparison
    assert "![Accuracy Ranking Plot](figures/accuracy_ranking_20260704.png)" in comparison
    assert "## Best Model" in comparison
    assert "## 12-Week Forecast" in comparison
    assert "Forecast generated by the best model: **sarimax**." in comparison
    assert "| 2026-07-06 | 5,000.00 |" in comparison
    assert "| 2026-09-21 | 5,011.00 |" in comparison
    assert "## Baseline Improvement" in comparison
    assert "## Forecast Range Comparison" in comparison
    assert "### Forecast Range Comparison Visualization" in comparison
    assert (
        "![Forecast Range Comparison Plot](figures/forecast_range_comparison_20260704.png)"
        in comparison
    )
    assert "## Business Insights" in comparison
    assert "## Limitations" in comparison
    assert "## Next Steps" in comparison

    for path, model in zip(
        paths[1:], ["linear_regression", "lightgbm", "prophet", "sarimax"], strict=True
    ):
        content = path.read_text(encoding="utf-8")
        assert "## Dataset Overview" in content
        assert "## External Regressor Review" in content
        assert "## Evaluation Metrics" in content
        assert "## Evaluation Interpretation" in content
        assert "## Train / Test Split and Test Evaluation" in content
        assert f"![Actual vs Predicted Plot](figures/{model}_evaluation_20260704.png)" in content
        assert "## 12-Week Forecast Summary" in content
        assert "### Forecast Visualization" in content
        assert f"![Actual and Forecasted Sales](figures/{model}_forecast_20260704.png)" in content
        assert "## Forecast Pattern Analysis" in content
        assert "## Model-Specific Interpretation" in content
        assert "## Notebook-Inspired Diagnostic Checklist" in content
        assert "Actual rows are used for backtesting and model fitting." in content
        assert "Baseline value:" in content
        assert "Back-Half Lift" in content


def test_generate_report_normalizes_html_output_to_markdown(tmp_path):
    config = _config_with_outputs(tmp_path)
    _write_model_comparison(config.output.evaluation_dir)
    _write_model_evaluation_predictions(config.output.evaluation_dir)
    _write_forecasts(config.output.forecast_dir)

    paths = generate_report(
        config,
        output=tmp_path / "advanced_report.html",
        report_date=date(2026, 7, 4),
    )

    assert paths[0].name == "advanced_report_20260704.md"
    assert paths[0].exists()
    assert paths[0].parent.name == "20260704"
    assert not (tmp_path / "20260704" / "advanced_report_20260704.html").exists()


def test_generate_report_handles_missing_data(tmp_path):
    config = _config_with_outputs(tmp_path)

    paths = generate_report(config, report_date=date(2026, 7, 4))

    assert len(paths) == 5
    for path in paths:
        assert path.exists()
        content = path.read_text(encoding="utf-8")
        assert "No data available" in content or "No evaluation data" in content
        assert "figures/" not in content
        if "comparison" in path.name:
            assert "*No ranking visualization available. Run evaluate first.*" in content
            assert (
                "*No forecast range comparison visualization available. Run forecast first.*"
                in content
            )
        else:
            assert "*No evaluation visualization available. Run evaluate first.*" in content
            assert "*No forecast visualization available. Run forecast first.*" in content


def _config_with_outputs(tmp_path):
    config = load_config("configs/base.yaml")
    output = OutputConfig(
        models_dir=tmp_path / "models",
        evaluation_dir=tmp_path / "evaluation",
        forecast_dir=tmp_path / "forecast",
        figures_dir=tmp_path / "figures",
        report_path=tmp_path / "model_comparison_report.md",
    )
    data_config = replace(config.data, path=tmp_path / "sales_data.csv")
    return replace(config, output=output, data=data_config)


def _write_model_comparison(evaluation_dir):
    evaluation_dir.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(
        [
            {
                "model_name": "baseline",
                "rmse": 100.0,
                "mae": 80.0,
                "mape": 0.10,
                "smape": 0.11,
                "wape": 0.12,
                "bias": -5.0,
                "baseline_improvement_rate": 0.0,
            },
            {
                "model_name": "linear_regression",
                "rmse": 90.0,
                "mae": 70.0,
                "mape": 0.09,
                "smape": 0.10,
                "wape": 0.11,
                "bias": -3.0,
                "baseline_improvement_rate": 0.10,
            },
            {
                "model_name": "lightgbm",
                "rmse": 95.0,
                "mae": 72.0,
                "mape": 0.095,
                "smape": 0.105,
                "wape": 0.115,
                "bias": -2.0,
                "baseline_improvement_rate": 0.05,
            },
            {
                "model_name": "prophet",
                "rmse": 105.0,
                "mae": 82.0,
                "mape": 0.12,
                "smape": 0.13,
                "wape": 0.14,
                "bias": 6.0,
                "baseline_improvement_rate": -0.05,
            },
            {
                "model_name": "sarimax",
                "rmse": 85.0,
                "mae": 65.0,
                "mape": 0.08,
                "smape": 0.09,
                "wape": 0.10,
                "bias": -1.0,
                "baseline_improvement_rate": 0.15,
            },
        ]
    ).to_csv(evaluation_dir / "model_comparison.csv", index=False)


def _write_model_evaluation_predictions(evaluation_dir):
    evaluation_dir.mkdir(parents=True, exist_ok=True)
    dates = pd.date_range("2026-06-01", periods=4, freq="W-MON")
    for model_name in ["linear_regression", "lightgbm", "prophet", "sarimax"]:
        pd.DataFrame(
            {
                "week_start_date": dates.strftime("%Y-%m-%d"),
                "actual": [1500.0, 1510.0, 1520.0, 1530.0],
                "prediction": [1490.0, 1505.0, 1525.0, 1535.0],
            }
        ).to_csv(evaluation_dir / f"{model_name}_evaluation.csv", index=False)


def _write_forecasts(forecast_dir):
    forecast_dir.mkdir(parents=True, exist_ok=True)
    dates = pd.date_range("2026-07-06", periods=12, freq="W-MON")
    model_start_values = {
        "baseline": 9000,
        "linear_regression": 1000,
        "lightgbm": 2000,
        "prophet": 3000,
        "sarimax": 5000,
    }
    for model_name, start_value in model_start_values.items():
        pd.DataFrame(
            {
                "week_start_date": dates.strftime("%Y-%m-%d"),
                "model_name": model_name,
                "prediction": [start_value + index for index in range(12)],
            }
        ).to_csv(forecast_dir / f"{model_name}_forecast.csv", index=False)


def _write_source_data(path):
    pd.DataFrame(
        {
            "Date": pd.date_range("2025-01-01", periods=100, freq="W-MON").strftime("%Y-%m-%d"),
            "Sales": [1000 + i * 10 for i in range(100)],
            "Record_Type": ["Actual"] * 100,
            "TVCM_GPR": [0.0] * 100,
            "Print_Media": [0.0] * 100,
            "Offline_Ads": [0.0] * 100,
            "Digital_Ads": [0.0] * 100,
        }
    ).to_csv(path, index=False)
